// Package integergroup implements the Azure ARM Integergroup service API
// version 1.0.0.
// 
// Test Infrastructure for AutoRest
package integergroup

// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

import (
    "github.com/Azure/go-autorest/autorest"
)

const (
    // APIVersion is the version of the Integergroup
    APIVersion = "1.0.0"

    // DefaultBaseURI is the default URI used for the service Integergroup
    DefaultBaseURI = "http://localhost"
)

// ManagementClient is the base client for Integergroup.
type ManagementClient struct {
    autorest.Client
    BaseURI string
    APIVersion string
}

// New creates an instance of the ManagementClient client.
func New() ManagementClient {
    return ManagementClient{
        Client: autorest.NewClientWithUserAgent(UserAgent()),
        BaseURI: DefaultBaseURI,
        APIVersion: APIVersion,
    }
}

