package stringgroup

// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

import (
    "github.com/Azure/go-autorest/autorest"
)    

// Colors enumerates the values for colors.
type Colors string

const (
    // BlueColor specifies the blue color state for colors.
    BlueColor Colors = "blue_color"
    // GreenColor specifies the green color state for colors.
    GreenColor Colors = "green-color"
    // Redcolor specifies the redcolor state for colors.
    Redcolor Colors = "red color"
)


// Error is
type Error struct {
    Status *int32 `json:"status,omitempty"`
    Message *string `json:"message,omitempty"`
}

// String is
type String struct {
    autorest.Response `json:"-"`
    Value *string `json:"value,omitempty"`
}

