package headergroup

// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

import (
// "github.com/Azure/go-autorest/autorest"
)

// GreyscaleColors enumerates the values for greyscale colors.
type GreyscaleColors string

const (
	// Black specifies the black state for greyscale colors.
	Black GreyscaleColors = "black"
	// GREY specifies the grey state for greyscale colors.
	GREY GreyscaleColors = "GREY"
	// White specifies the white state for greyscale colors.
	White GreyscaleColors = "White"
)

// Error is
type Error struct {
	Status  *int32  `json:"status,omitempty"`
	Message *string `json:"message,omitempty"`
}
